using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Threading;

namespace Ranger.View
{
    /// <summary>
    /// Interaction logic for DatabaseView.xaml
    /// </summary>
    public partial class DatabaseView : UserControl
    {
        public DatabaseView()
        {
            InitializeComponent();
        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = sender as DataGrid;

            if (grid.Columns.Count > 0)
            {
                foreach (var col in grid.Columns)
                    col.Width = DataGridLength.Auto;

                // 🔥 utolsó oszlop tölti ki
                grid.Columns.Last().Width = new DataGridLength(1, DataGridLengthUnitType.Star);
            }
        }

        private void DataGrid_Loaded(object sender, RoutedEventArgs e)
        {
            var grid = sender as DataGrid;

            Dispatcher.BeginInvoke(new Action(() =>
            {
                if (grid.Columns.Count > 0)
                {
                    foreach (var col in grid.Columns)
                        col.Width = DataGridLength.Auto;

                    // utolsó oszlop tölti ki
                    grid.Columns[^1].Width = new DataGridLength(1, DataGridLengthUnitType.Star);
                }
            }), DispatcherPriority.Loaded);
        }
    }
}
